"""Browser 核心模块：会话管理、事件系统、配置、视图。"""

from .action_result import ActionResult
from .events import (
    AgentFocusChangedEvent,
    BrowserConnectedEvent,
    BrowserErrorEvent,
    BrowserLaunchEvent,
    BrowserLaunchResult,
    BrowserReconnectedEvent,
    BrowserReconnectingEvent,
    BrowserStartEvent,
    BrowserStateRequestEvent,
    BrowserStopEvent,
    BrowserStoppedEvent,
    ClickCoordinateEvent,
    ClickElementEvent,
    CloseTabEvent,
    ElementSelectedEvent,
    GetDropdownOptionsEvent,
    GoBackEvent,
    GoForwardEvent,
    NavigateToUrlEvent,
    NavigationCompleteEvent,
    NavigationStartedEvent,
    RefreshEvent,
    ScreenshotEvent,
    ScrollEvent,
    ScrollToTextEvent,
    SelectDropdownOptionEvent,
    SendKeysEvent,
    SwitchTabEvent,
    TabClosedEvent,
    TabCreatedEvent,
    TypeTextEvent,
    WaitEvent,
)
from .profile import BrowserProfile, ProxySettings
from .session import BrowserSession, CDPSession, Target
from .session_manager import SessionManager
from .views import BrowserError, BrowserStateHistory, BrowserStateSummary, TabInfo
from .watchdog_base import BaseWatchdog

__all__ = [
    "ActionResult",
    "AgentFocusChangedEvent",
    "BaseWatchdog",
    "BrowserConnectedEvent",
    "BrowserError",
    "BrowserErrorEvent",
    "BrowserLaunchEvent",
    "BrowserLaunchResult",
    "BrowserProfile",
    "BrowserReconnectedEvent",
    "BrowserReconnectingEvent",
    "BrowserSession",
    "BrowserStartEvent",
    "BrowserStateHistory",
    "BrowserStateRequestEvent",
    "BrowserStateSummary",
    "BrowserStopEvent",
    "BrowserStoppedEvent",
    "CDPSession",
    "ClickCoordinateEvent",
    "ClickElementEvent",
    "CloseTabEvent",
    "ElementSelectedEvent",
    "GetDropdownOptionsEvent",
    "GoBackEvent",
    "GoForwardEvent",
    "NavigateToUrlEvent",
    "NavigationCompleteEvent",
    "NavigationStartedEvent",
    "ProxySettings",
    "RefreshEvent",
    "ScreenshotEvent",
    "ScrollEvent",
    "ScrollToTextEvent",
    "SelectDropdownOptionEvent",
    "SendKeysEvent",
    "SessionManager",
    "SwitchTabEvent",
    "TabClosedEvent",
    "TabCreatedEvent",
    "TabInfo",
    "Target",
    "TypeTextEvent",
    "WaitEvent",
]
